// web/components/AgentChat.vue
<script setup lang="ts">
interface Props {
  agentId: string
  threadId: string
  userId: string
  model?: string
}

const props = defineProps<Props>()

const { messages, input, setMessages, addUserMessage } = useAgentChat()
const { runAgent } = useAgentRun({
  agentId: props.agentId,
  threadId: props.threadId,
  userId: props.userId
})

const isGenerating = ref(false)
const messagesEndRef = ref<HTMLElement | null>(null)

const { chats: historyChats, loadMore, hasMore, isLoading: isLoadingHistory } = useThreadHistory(
  props.threadId,
  props.userId
)

const historyMessages = computed(() =>
  historyChats.value.flatMap((chat) =>
    chat.messages.map((msg) => ({
      id: msg.id,
      role: msg.role as 'user' | 'assistant' | 'system' | 'tool',
      content: typeof msg.content === 'string' ? msg.content : (msg.content as any)?.text || ''
    }))
  )
)

const allMessages = computed(() => [...historyMessages.value, ...messages.value])

const scrollToBottom = () => {
  nextTick(() => {
    messagesEndRef.value?.scrollIntoView({ behavior: 'smooth' })
  })
}

watch(() => isLoadingHistory.value, (loading) => {
  if (!loading) {
    scrollToBottom()
  }
})

onMounted(() => {
  if (props.threadId && props.userId) {
    loadMore()
  }
  scrollToBottom()
})

const handleSSEEvent = (event: any) => {
  switch (event.type) {
    case 'TEXT_MESSAGE_START':
      break

    case 'TEXT_MESSAGE_CONTENT':
      setMessages((prev: any[]) => {
        const lastMsg = prev[prev.length - 1]
        if (lastMsg?.role === 'assistant' && lastMsg.id.startsWith('temp_')) {
          return [
            ...prev.slice(0, -1),
            { ...lastMsg, content: (lastMsg.content as string) + event.data.content }
          ]
        } else {
          return [
            ...prev,
            { id: 'temp_' + Date.now(), role: 'assistant' as const, content: event.data.content }
          ]
        }
      })
      break

    case 'TEXT_MESSAGE_END':
      setMessages((prev: any[]) => {
        const lastMsg = prev[prev.length - 1]
        if (lastMsg?.role === 'assistant' && lastMsg.id.startsWith('temp_')) {
          return [...prev.slice(0, -1), { ...lastMsg, id: crypto.randomUUID() }]
        }
        return prev
      })
      break

    case 'RUN_STARTED':
      isGenerating.value = true
      break

    case 'RUN_FINISHED':
      isGenerating.value = false
      break

    case 'RUN_ERROR':
      isGenerating.value = false
      console.error('Error:', event.data.error)
      break

    default:
      break
  }
}

const handleScroll = (e: Event) => {
  const target = e.target as HTMLElement
  if (target.scrollTop === 0 && hasMore.value && !isLoadingHistory.value) {
    loadMore()
  }
}

const handleSubmit = async () => {
  if (!input.value.trim() || isGenerating.value) return

  const userInput = input.value.trim()
  const userMsgId = crypto.randomUUID()
  addUserMessage(userInput)

  await runAgent({
    messages: [
      ...allMessages.value.map((m) => ({ id: m.id, role: m.role, content: m.content })),
      { id: userMsgId, role: 'user' as const, content: userInput }
    ],
    tools: [],
    context: [],
    forwardedProps: { agentId: props.agentId, userId: props.userId, model: props.model }
  })
}

const handleKeydown = (e: KeyboardEvent) => {
  if (!e.shiftKey && (e.target as HTMLElement).tagName !== 'TEXTAREA') return
  if (!e.shiftKey && e.key === 'Enter') {
    e.preventDefault()
    handleSubmit()
  }
}
</script>

<template>
  <div class="flex flex-col h-full bg-muted text-default">
    <div class="flex-1 overflow-auto p-6" @scroll="handleScroll">
      <div v-if="isLoadingHistory" class="text-center py-4 text-muted">
        加载更多...
      </div>

      <div v-if="allMessages.length === 0" class="text-center text-muted mt-24">
        开始对话吧！
      </div>

      <div
        v-for="(msg, index) in allMessages"
        :key="msg.id || index"
        class="mb-4 flex"
        :class="msg.role === 'user' ? 'justify-end' : 'justify-start'"
      >
        <div class="flex items-start gap-2 max-w-2xl">
          <div
            v-if="msg.role !== 'user'"
            class="w-9 h-9 rounded-full bg-primary text-inverted flex items-center justify-center text-sm flex-shrink-0"
          >
            AI
          </div>
          <div
            class="px-4 py-3 shadow-sm whitespace-pre-wrap break-words"
            :class="msg.role === 'user'
              ? 'bg-primary text-inverted rounded-2xl rounded-tr-sm'
              : 'bg-default text-default border border-default rounded-2xl rounded-tl-sm'"
          >
            {{ String(msg.content) }}
          </div>
          <div
            v-if="msg.role === 'user'"
            class="w-9 h-9 rounded-full bg-inverted text-inverted flex items-center justify-center text-sm flex-shrink-0"
          >
            我
          </div>
        </div>
      </div>

      <div v-if="isGenerating" class="mb-4 flex justify-start">
        <div class="flex items-start gap-2 max-w-2xl">
          <div class="w-9 h-9 rounded-full bg-primary text-inverted flex items-center justify-center text-sm flex-shrink-0">
            AI
          </div>
          <div class="px-4 py-3 bg-default border border-default rounded-2xl rounded-tl-sm shadow-sm">
            <span class="text-muted">正在思考...</span>
          </div>
        </div>
      </div>

      <div ref="messagesEndRef" />
    </div>

    <div class="p-4 bg-default border-t border-default">
      <UTextarea
        v-model="input"
        placeholder="输入消息..."
        :disabled="isGenerating"
        :rows="1"
        class="w-full"
        @keydown="handleKeydown"
      />
    </div>
  </div>
</template>

// web/src/components/agent-chat.tsx
'use client';

/**
 * AgentChat组件 - 使用 Ant Design Vue
 */
import { useState, useCallback, useRef, useEffect } from 'react';
import { Input, Spin, Avatar } from 'antd';
import { useAgentRun, useAgentChat } from '@/hooks/use-agent-run';
import { useThreadHistory } from '@/hooks/use-thread-history';

interface AgentChatProps {
  agentId: string;
  threadId: string;
  userId: string;
  model?: string;
}

export function AgentChat({ agentId, threadId, userId, model }: AgentChatProps) {
  const { messages, input, setInput, setMessages, addUserMessage } = useAgentChat();
  const [isGenerating, setIsGenerating] = useState(false);

  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = useCallback(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, []);

  const {
    chats: historyChats,
    loadMore,
    hasMore,
    isLoading: isLoadingHistory,
  } = useThreadHistory(threadId, userId);

  const historyMessages = historyChats.flatMap((chat) =>
    chat.messages.map((msg) => ({
      id: msg.id,
      role: msg.role as 'user' | 'assistant' | 'system' | 'tool',
      content: typeof msg.content === 'string' ? msg.content : (msg.content as any)?.text || '',
    }))
  );

  const allMessages = [...historyMessages, ...messages];

  useEffect(() => {
    if (!isLoadingHistory) {
      scrollToBottom();
    }
  }, [historyChats, isLoadingHistory, scrollToBottom]);

  useEffect(() => {
    if (threadId && userId) {
      loadMore();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [threadId, userId]);

  const handleSSEEvent = useCallback((event: any) => {
    switch (event.type) {
      case 'TEXT_MESSAGE_START':
        break;

      case 'TEXT_MESSAGE_CONTENT':
        setMessages((prev) => {
          const lastMsg = prev[prev.length - 1];
          if (lastMsg?.role === 'assistant' && lastMsg.id.startsWith('temp_')) {
            return [
              ...prev.slice(0, -1),
              { ...lastMsg, content: (lastMsg.content as string) + event.data.content },
            ];
          } else {
            return [
              ...prev,
              { id: 'temp_' + Date.now(), role: 'assistant' as const, content: event.data.content },
            ];
          }
        });
        break;

      case 'TEXT_MESSAGE_END':
        setMessages((prev) => {
          const lastMsg = prev[prev.length - 1];
          if (lastMsg?.role === 'assistant' && lastMsg.id.startsWith('temp_')) {
            return [...prev.slice(0, -1), { ...lastMsg, id: crypto.randomUUID() }];
          }
          return prev;
        });
        setIsGenerating(false);
        break;

      case 'RUN_STARTED':
        setIsGenerating(true);
        break;

      case 'RUN_FINISHED':
        setIsGenerating(false);
        break;

      case 'RUN_ERROR':
        setIsGenerating(false);
        alert('Error: ' + event.data.error);
        break;

      default:
        break;
    }
  }, [setMessages]);

  const handleScroll = useCallback(
    (e: React.UIEvent<HTMLDivElement>) => {
      const target = e.target as HTMLDivElement;
      if (target.scrollTop === 0 && hasMore && !isLoadingHistory) {
        loadMore();
      }
    },
    [hasMore, isLoadingHistory, loadMore]
  );

  const { runAgent } = useAgentRun({ agentId, threadId, userId, onMessage: handleSSEEvent });

  const handleSubmit = async () => {
    if (!input.trim() || isGenerating) return;

    const userInput = input.trim();
    const userMsgId = crypto.randomUUID();
    addUserMessage(userInput);

    await runAgent({
      messages: [
        ...allMessages.map((m) => ({ id: m.id, role: m.role, content: m.content })),
        { id: userMsgId, role: 'user' as const, content: userInput },
      ],
      tools: [],
      context: [],
      forwardedProps: { agentId, userId, model },
    });
  };

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column', background: '#f5f5f5' }}>
      {/* 消息列表 */}
      <div
        style={{ flex: 1, overflow: 'auto', padding: '24px' }}
        onScroll={handleScroll}
      >
        {isLoadingHistory && (
          <div style={{ textAlign: 'center', padding: '16px' }}>
            <Spin tip="加载更多..." />
          </div>
        )}

        {allMessages.length === 0 && (
          <div style={{ textAlign: 'center', color: '#999', marginTop: '100px' }}>
            开始对话吧！
          </div>
        )}

        {allMessages.map((msg, index) => (
          <div
            key={msg.id || index}
            style={{
              marginBottom: '16px',
              display: 'flex',
              flexDirection: 'column',
              alignItems: msg.role === 'user' ? 'flex-end' : 'flex-start',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'flex-start', gap: '8px', maxWidth: '70%' }}>
              {msg.role !== 'user' && <Avatar style={{ background: '#1890ff' }}>AI</Avatar>}
              <div
                style={{
                  padding: '12px 16px',
                  borderRadius: msg.role === 'user' ? '16px 16px 4px 16px' : '16px 16px 16px 4px',
                  background: msg.role === 'user' ? '#1890ff' : '#fff',
                  color: msg.role === 'user' ? '#fff' : '#333',
                  boxShadow: '0 1px 2px rgba(0,0,0,0.1)',
                  whiteSpace: 'pre-wrap',
                  wordBreak: 'break-word',
                }}
              >
                {String(msg.content)}
              </div>
              {msg.role === 'user' && <Avatar style={{ background: '#52c41a' }}>我</Avatar>}
            </div>
          </div>
        ))}

        {isGenerating && (
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: '8px', marginBottom: '16px' }}>
            <Avatar style={{ background: '#1890ff' }}>AI</Avatar>
            <div style={{ padding: '12px 16px', borderRadius: '16px', background: '#fff' }}>
              <Spin size="small" tip="正在思考..." />
            </div>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* 输入框 */}
      <div style={{ padding: '16px 24px', background: '#fff', borderTop: '1px solid #f0f0f0' }}>
        <Input.TextArea
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="输入消息..."
          disabled={isGenerating}
          autoSize={{ minRows: 1, maxRows: 4 }}
          onPressEnter={(e) => {
            if (!e.shiftKey) {
              e.preventDefault();
              handleSubmit();
            }
          }}
          style={{ borderRadius: '8px' }}
        />
      </div>
    </div>
  );
}
