// web/components/Sidebar.vue
<script setup lang="ts">
import type { ThreadItem } from '~/types'

interface Props {
  threads: ThreadItem[]
  currentThreadId: string
  isLoading: boolean
}

const props = defineProps<Props>()

const emit = defineEmits<{
  (e: 'select', threadId: string): void
  (e: 'new'): void
}>()
</script>

<template>
  <div class="flex flex-col h-full">
    <div class="p-3">
      <UButton block @click="emit('new')">
        + 新建会话
      </UButton>
    </div>

    <div class="flex-1 overflow-auto">
      <div v-if="isLoading" class="text-center py-10 text-muted">
        加载中...
      </div>
      <div v-else-if="threads.length === 0" class="text-center py-10 text-muted">
        暂无会话
      </div>
      <div v-else>
        <div
          v-for="thread in threads"
          :key="thread.threadId"
          class="px-4 py-3 cursor-pointer border-l-3 transition-colors"
          :class="thread.threadId === currentThreadId
            ? 'bg-elevated border-l-primary'
            : 'border-l-default hover:bg-elevated'"
          @click="emit('select', thread.threadId)"
        >
          <div class="text-sm text-highlighted">{{ thread.name }}</div>
          <div class="text-xs text-muted">
            {{ new Date(thread.createdAt).toLocaleString('zh-CN', {
              month: 'numeric',
              day: 'numeric',
              hour: '2-digit',
              minute: '2-digit'
            }) }}
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// web/src/components/sidebar.tsx
'use client';

import { List, Button, Spin } from 'antd';
import { ThreadItem } from '@/hooks/use-thread-list';

interface SidebarProps {
  threads: ThreadItem[];
  currentThreadId: string;
  onSelectThread: (threadId: string) => void;
  onNewThread: () => void;
  isLoading: boolean;
}

export function Sidebar({ threads, currentThreadId, onSelectThread, onNewThread, isLoading }: SidebarProps) {
  return (
    <div style={{
      width: 280,
      borderRight: '1px solid #f0f0f0',
      background: '#fafafa',
      display: 'flex',
      flexDirection: 'column',
      height: '100%',
    }}>
      {/* 新建会话按钮 */}
      <div style={{ padding: '12px' }}>
        <Button
          type="primary"
          onClick={onNewThread}
          block
        >
          + 新建会话
        </Button>
      </div>

      {/* 会话列表 */}
      <div style={{ flex: 1, overflow: 'auto' }}>
        {isLoading ? (
          <div style={{ textAlign: 'center', padding: '40px 0' }}>
            <Spin />
          </div>
        ) : threads.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '40px 0', color: '#999' }}>
            暂无会话
          </div>
        ) : (
          <List
            dataSource={threads}
            renderItem={(thread) => (
              <List.Item
                key={thread.threadId}
                onClick={() => onSelectThread(thread.threadId)}
                style={{
                  padding: '12px 16px',
                  cursor: 'pointer',
                  background: thread.threadId === currentThreadId ? '#e6f7ff' : 'transparent',
                  borderLeft: thread.threadId === currentThreadId ? '3px solid #1890ff' : '3px solid transparent',
                }}
              >
                <List.Item.Meta
                  title={thread.name}
                  description={new Date(thread.createdAt).toLocaleString('zh-CN', {
                    month: 'numeric',
                    day: 'numeric',
                    hour: '2-digit',
                    minute: '2-digit',
                  })}
                />
              </List.Item>
            )}
          />
        )}
      </div>
    </div>
  );
}
